package com.video.player.videoplayer.xvxvideoplayer.gallery.util;

public enum VP_GalleryFilterType {
    VP_NONE, VP_CONTRAST, VP_BRIGHTNESS, VP_BLUR, VP_GRAY, VP_COLOR, VP_VIGNETTE, VP_INVERT, VP_PIXELATION, VP_SEPIA, VP_SKETCH,
    VP_TOON, VP_SWIRL, VP_GAMMA, VP_SATURATION, VP_LUMINANCE, VP_HUE, VP_CROSSHATCH, VP_SOBE, VP_FALSE_COLOR, VP_HALFTONE, VP_KUWAHARA,
    VP_WHITE_BALANCE
}
